Repository inst-support-eng/panda-pto, pull requests merged in 2019-05, with the labels that each got.

#71 Admin agents display
  app/assets/javascripts/admin/usersModal.js
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/users.scss
  app/controllers/pto_requests_controller.rb
  app/views/admin/index.html.erb
  app/views/requests_mailer/sick_make_up_email.html.erb
  app/views/requests_mailer/sick_make_up_email.txt.erb
  app/views/users/show.html.erb
  config/routes.rb
Labels: bug, enhancement

#74 add daily coverage mailer
  README.md
  app/mailers/coverage_mailer.rb
  app/views/coverage_mailer/off_today.html.erb
  lib/tasks/mail.rake
  spec/mailers/coverage_mailer_spec.rb
  spec/mailers/previews/coverage_mailer_preview.rb
Labels: enhancement

#75 fixes issue 73
  app/controllers/pto_requests_controller.rb
Labels: bug

#81 Issue 80
  app/assets/stylesheets/admin.scss
  app/views/admin/index.html.erb
Labels: bug

#86 Issue 84
  app/assets/stylesheets/partials/calendar.scss
  app/views/devise/registrations/edit.html.erb
  app/views/pages/pages_path/calendar/_sidebar.html.erb
  app/views/users/show.html.erb
Labels: bug, debt
