Repository inst-support-eng/panda-pto, pull requests merged in 2019-07, with the labels that each got.

#141 fix for issue 137
  app/assets/javascripts/calendar/modal.js
Labels: bug

#142 move outbound address to env var - issue #140
  app/mailers/coverage_mailer.rb
  app/mailers/registration_mailer.rb
  app/mailers/requests_mailer.rb
  config/initializers/devise.rb
  db/migrate/20190327003202_add_position_to_agent.rb
  db/migrate/20190327015832_add_admin_to_agent.rb
  db/migrate/20190506201016_add_start_date_to_agent.rb
  db/migrate/20190508195442_drop_agents.rb
  db/migrate/20190508195510_drop_date_values.rb
  db/schema.rb
Labels: debt

#148 fixes issue_147
  app/assets/javascripts/calendar/modal.js
Labels: bug

#146 Sync users from Hamanity
  README.md
  app/assets/javascripts/calendar/modal.js
  app/models/user.rb
  app/views/admin/index.html.erb
  lib/humanity_api.rb
  lib/tasks/pto_tasks.rake
Labels: enhancement

#157 Tooltips
  app/assets/javascripts/calendar/calendar.js
  app/assets/javascripts/calendar/sidebar.js
  app/assets/stylesheets/partials/calendar.scss
  app/controllers/pages_controller.rb
  app/views/pages/pages_path/calendar/_sidebar.html.erb
Labels: enhancement

#149 Agents-table width matches working-grid
  app/assets/stylesheets/admin.scss
Labels: bug
