Repository inst-support-eng/panda-pto, pull requests merged in 2019-08, with the labels that each got.

#163 Issue 162
  app/assets/javascripts/calendar/modal.js
  app/controllers/pto_requests_controller.rb
Labels: bug

#167 Pretty flash alert/notice + disambiguity
  app/assets/javascripts/alert.js
  app/assets/stylesheets/base/default.scss
  app/assets/stylesheets/users.scss
  app/controllers/calendar_l2s_controller.rb
  app/controllers/calendar_l3s_controller.rb
  app/controllers/calendar_sups_controller.rb
  app/controllers/calendars_controller.rb
  app/controllers/pto_requests_controller.rb
  app/controllers/users_controller.rb
  app/views/layouts/application.html.erb
  app/views/users/show.html.erb
Labels: debt

#165 Request improvements
  app/controllers/pages_controller.rb
  app/controllers/pto_requests_controller.rb
  app/controllers/registrations_controller.rb
  app/controllers/users_controller.rb
  app/models/pto_request.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.erb
  app/views/pages/pages_path/calendar/_sidebar.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20190727020551_add_is_deleted_to_pto_requests.rb
  db/schema.rb
  lib/humanity_api.rb
  lib/update_price.rb
Labels: debt, enhancement

#174 Modal sidebar fixes
  app/assets/stylesheets/partials/calendar.scss
  app/controllers/pto_requests_controller.rb
  lib/legalizer.rb
Labels: bug
